### ISSUE TITLE
omg.txt?

### ISSUE THREAD

**Issue by masaiaaaa** [senadkurtisi/pytorch-image-captioning#13]
what is "omg.txt" in config.json？

**Comment by senadkurtisi** [comment]
Thank you for mentioning this! Can't believe it's been over a year since this code was pushed and no one mentioned it until now. :)

Content of the [config.json](https://github.com/senadkurtisi/pytorch-image-captioning/blob/main/config.json) is modified an now the `dataset_path` entry is no longer `omg.txt` but rather now it is `flickr_data.txt`.

Reasoning behind old name (which was admittedly a bit odd) is a large number of duplicated files acquired from multiple sources.
But, essentially this file is actually the one which can be downloaded from the official source of the Flickr8k dataset. You can read more about the dataset in the [README](https://github.com/senadkurtisi/pytorch-image-captioning#readme) of this project.
